spring:
  application:
    name: ChatApp
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
    mongodb:
      uri: mongodb://${USER_DB}:${PASSWORD_DB}@localhost:27017/chat
  mail:
    host: ${SMTP_HOST}
    username: ${SMTP_EMAIL}
    port: ${SMTP_PORT}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 2GB
logging:
  level:
    org:
      springframework:
        security: DEBUG
s3:
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  region: ${S3_REGION}
  bucket: ${S3_BUCKET}
jwt:
  signer-key: ${SIGNER_KEY}
  expiration-time: ${EXPIRATION_TIME}
