spring:
  datasource:
    url: jdbc:h2:mem:test
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  mail:
    host: ${SMTP_HOST}
    username: ${SMTP_EMAIL}
    port: ${SMTP_PORT}
    password: ${SMTP_PASSWORD}
    ssl:
      enabled: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration


s3:
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  region: ${S3_REGION}
  bucket: ${S3_BUCKET}
jwt:
  signer-key: ${SIGNER_KEY}
  expiration-time: 1

