spring:
  datasource:
    url: jdbc:h2:mem:test
  mail:
    host: ${SMTP_HOST}
    username: ${SMTP_EMAIL}
    port: ${SMTP_PORT}
    password: ${SMTP_PASSWORD}
    ssl:
      enabled: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
rsa:
  private-key: ${RSA_PRIVATE_KEY}
  public-key: ${RSA_PUBLIC_KEY}
s3:
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  region: ${S3_REGION}
  bucket: ${S3_BUCKET}

